"""v2 baseline

Revision ID: 975fb339662f
Revises:
Create Date: 2026-07-24 17:24:37.443230
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '975fb339662f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('byte_size >= 0', name='ck_evidence_artifact_size'),
    sa.CheckConstraint('length(sha256) = 64', name='ck_evidence_artifact_sha_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('market_time_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_indicator_time', 'market_time_series', ['indicator_name', 'timestamp'], unique=True)
    op.create_table('raw_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_AI', 'PROCESSED', 'IGNORED_NOISE', name='intelligencestatus'), nullable=False),
    sa.Column('target_panel_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_raw_published', 'raw_intelligence', ['published_at'], unique=False)
    op.create_index('idx_raw_source', 'raw_intelligence', ['source_name'], unique=False)
    op.create_index('idx_raw_status', 'raw_intelligence', ['status'], unique=False)
    op.create_table('strategic_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategic_advice', sa.Text(), nullable=False),
    sa.Column('display_type', sa.String(length=50), nullable=False),
    sa.Column('geo_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('affected_panels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insight_created', 'strategic_insights', ['created_at'], unique=False)
    op.create_index('idx_insight_role', 'strategic_insights', ['role'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comparison_key', sa.String(length=500), nullable=False),
    sa.Column('observation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_version', sa.String(length=100), nullable=False),
    sa.Column('tolerance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'PASSED', 'CONFLICT', 'NEEDS_REVIEW', 'REJECTED', name='v2_verification_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_comparison_key'), 'validation_runs', ['comparison_key'], unique=False)
    op.create_index(op.f('ix_validation_runs_state'), 'validation_runs', ['state'], unique=False)
    op.create_table('vehicle_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vehicle_brand', 'vehicle_models', ['brand_name'], unique=False)
    op.create_index('idx_vehicle_specs', 'vehicle_models', ['specs'], unique=False, postgresql_using='gin')
    op.create_table('intelligence_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_id', sa.UUID(), nullable=False),
    sa.Column('title_brief', sa.String(length=255), nullable=False),
    sa.Column('target_panel_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geolocation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('involved_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_id'], ['raw_intelligence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_info_created', 'intelligence_info', ['created_at'], unique=False)
    op.create_index('idx_info_panels', 'intelligence_info', ['target_panel_ids'], unique=False, postgresql_using='gin')
    op.create_table('review_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_run_id', sa.UUID(), nullable=True),
    sa.Column('observation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'APPROVED', 'REJECTED', 'NEEDS_INFORMATION', name='v2_review_state'), nullable=False),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cases_state'), 'review_cases', ['state'], unique=False)
    op.create_index(op.f('ix_review_cases_validation_run_id'), 'review_cases', ['validation_run_id'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('predecessor_id', sa.UUID(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trust_state', sa.Enum('UNVERIFIED', 'VERIFIED', 'REJECTED', 'LEGACY_UNVERIFIED', name='v2_trust_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['evidence_artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['source_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', 'retrieved_at', 'artifact_id', name='uq_source_snapshot_capture')
    )
    op.create_index('idx_source_snapshot_url_retrieved', 'source_snapshots', ['canonical_url', 'retrieved_at'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source_key'), 'source_snapshots', ['source_key'], unique=False)
    op.create_index(op.f('ix_source_snapshots_trust_state'), 'source_snapshots', ['trust_state'], unique=False)
    op.create_table('structured_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_id', sa.UUID(), nullable=False),
    sa.Column('title_brief', sa.String(length=255), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signal_type', sa.Enum('PRICE_WAR', 'SUPPLY_CHAIN', 'POLICY', 'PRODUCT_LAUNCH', 'NEGATIVE_PR', 'OTHER', name='signaltype'), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('geolocation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('involved_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_panel_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_id'], ['raw_intelligence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_created', 'structured_signals', ['created_at'], unique=False)
    op.create_index('idx_signal_entities', 'structured_signals', ['involved_entities'], unique=False, postgresql_using='gin')
    op.create_index('idx_signal_geolocation', 'structured_signals', ['geolocation'], unique=False, postgresql_using='gin')
    op.create_index('idx_signal_score', 'structured_signals', ['impact_score'], unique=False)
    op.create_index('idx_signal_type', 'structured_signals', ['signal_type'], unique=False)
    op.create_table('evidence_fragments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('locator_type', sa.String(length=50), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_text_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'locator_type', 'locator', name='uq_evidence_fragment_locator')
    )
    op.create_index(op.f('ix_evidence_fragments_snapshot_id'), 'evidence_fragments', ['snapshot_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_case_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.Enum('OPEN', 'APPROVED', 'REJECTED', 'NEEDS_INFORMATION', name='v2_review_state'), nullable=False),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_case_id'], ['review_cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['review_decisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_outcome'), 'review_decisions', ['outcome'], unique=False)
    op.create_index(op.f('ix_review_decisions_review_case_id'), 'review_decisions', ['review_case_id'], unique=False)
    op.create_table('metric_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panel_version_key', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('metric_key', sa.String(length=255), nullable=False),
    sa.Column('evidence_fragment_id', sa.UUID(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('raw_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('geographic_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_model', sa.String(length=255), nullable=True),
    sa.Column('extraction_prompt_version', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trust_state', sa.Enum('UNVERIFIED', 'VERIFIED', 'REJECTED', 'LEGACY_UNVERIFIED', name='v2_metric_trust_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_metric_observation_confidence'),
    sa.CheckConstraint('period_end IS NULL OR period_start IS NULL OR period_end >= period_start', name='ck_metric_observation_period'),
    sa.ForeignKeyConstraint(['evidence_fragment_id'], ['evidence_fragments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['metric_observations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metric_observation_lookup', 'metric_observations', ['panel_version_key', 'metric_key', 'observed_at'], unique=False)
    op.create_index(op.f('ix_metric_observations_evidence_fragment_id'), 'metric_observations', ['evidence_fragment_id'], unique=False)
    op.create_index(op.f('ix_metric_observations_metric_key'), 'metric_observations', ['metric_key'], unique=False)
    op.create_index(op.f('ix_metric_observations_panel_version_key'), 'metric_observations', ['panel_version_key'], unique=False)
    op.create_index(op.f('ix_metric_observations_trust_state'), 'metric_observations', ['trust_state'], unique=False)
    op.create_table('calculation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('output_observation_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('input_observation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.String(length=100), nullable=False),
    sa.Column('replay_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['output_observation_id'], ['metric_observations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('output_observation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_runs')
    op.drop_index(op.f('ix_metric_observations_trust_state'), table_name='metric_observations')
    op.drop_index(op.f('ix_metric_observations_panel_version_key'), table_name='metric_observations')
    op.drop_index(op.f('ix_metric_observations_metric_key'), table_name='metric_observations')
    op.drop_index(op.f('ix_metric_observations_evidence_fragment_id'), table_name='metric_observations')
    op.drop_index('idx_metric_observation_lookup', table_name='metric_observations')
    op.drop_table('metric_observations')
    op.drop_index(op.f('ix_review_decisions_review_case_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_outcome'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_evidence_fragments_snapshot_id'), table_name='evidence_fragments')
    op.drop_table('evidence_fragments')
    op.drop_index('idx_signal_type', table_name='structured_signals')
    op.drop_index('idx_signal_score', table_name='structured_signals')
    op.drop_index('idx_signal_geolocation', table_name='structured_signals', postgresql_using='gin')
    op.drop_index('idx_signal_entities', table_name='structured_signals', postgresql_using='gin')
    op.drop_index('idx_signal_created', table_name='structured_signals')
    op.drop_table('structured_signals')
    op.drop_index(op.f('ix_source_snapshots_trust_state'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_source_key'), table_name='source_snapshots')
    op.drop_index('idx_source_snapshot_url_retrieved', table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_review_cases_validation_run_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_state'), table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index('idx_info_panels', table_name='intelligence_info', postgresql_using='gin')
    op.drop_index('idx_info_created', table_name='intelligence_info')
    op.drop_table('intelligence_info')
    op.drop_index('idx_vehicle_specs', table_name='vehicle_models', postgresql_using='gin')
    op.drop_index('idx_vehicle_brand', table_name='vehicle_models')
    op.drop_table('vehicle_models')
    op.drop_index(op.f('ix_validation_runs_state'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_comparison_key'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index('idx_insight_role', table_name='strategic_insights')
    op.drop_index('idx_insight_created', table_name='strategic_insights')
    op.drop_table('strategic_insights')
    op.drop_index('idx_raw_status', table_name='raw_intelligence')
    op.drop_index('idx_raw_source', table_name='raw_intelligence')
    op.drop_index('idx_raw_published', table_name='raw_intelligence')
    op.drop_table('raw_intelligence')
    op.drop_index('idx_market_indicator_time', table_name='market_time_series')
    op.drop_table('market_time_series')
    op.drop_table('evidence_artifacts')
    postgresql.ENUM(name='v2_review_state').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='v2_metric_trust_state').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='v2_trust_state').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='v2_verification_state').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='signaltype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='intelligencestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
