"""add source pools and collection jobs

Revision ID: a46a24af8bbf
Revises: 975fb339662f
Create Date: 2026-07-24 17:28:01.103608
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a46a24af8bbf'
down_revision: Union[str, None] = '975fb339662f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('dashboard_version_key', sa.String(length=255), nullable=True),
    sa.Column('discovery_query', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_source_pools_dashboard_version_key'), 'source_pools', ['dashboard_version_key'], unique=False)
    op.create_table('source_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('HTML', 'PDF', 'CSV', 'XLSX', 'RSS', 'API', name='v2_source_kind'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('credential_reference', sa.String(length=500), nullable=True),
    sa.Column('robots_url', sa.Text(), nullable=True),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('global_reputation', sa.Float(), nullable=False),
    sa.Column('topic_authority', sa.Float(), nullable=False),
    sa.Column('refresh_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('global_reputation >= 0 AND global_reputation <= 1', name='ck_source_global_reputation'),
    sa.CheckConstraint('topic_authority >= 0 AND topic_authority <= 1', name='ck_source_topic_authority'),
    sa.ForeignKeyConstraint(['pool_id'], ['source_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'key', name='uq_source_definition_pool_key')
    )
    op.create_index(op.f('ix_source_definitions_pool_id'), 'source_definitions', ['pool_id'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_definition_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'BLOCKED', 'CANCELLED', name='v2_collection_job_state'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('policy_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('attempt_count >= 0', name='ck_collection_job_attempt_count'),
    sa.CheckConstraint('max_attempts > 0', name='ck_collection_job_max_attempts'),
    sa.ForeignKeyConstraint(['result_snapshot_id'], ['source_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_definition_id'], ['source_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_collection_job_state_requested', 'collection_jobs', ['state', 'requested_at'], unique=False)
    op.create_index(op.f('ix_collection_jobs_source_definition_id'), 'collection_jobs', ['source_definition_id'], unique=False)
    op.create_index(op.f('ix_collection_jobs_state'), 'collection_jobs', ['state'], unique=False)
    op.create_table('human_action_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_job_id', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='v2_human_action_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_action_requests_collection_job_id'), 'human_action_requests', ['collection_job_id'], unique=False)
    op.create_index(op.f('ix_human_action_requests_state'), 'human_action_requests', ['state'], unique=False)
    op.add_column('source_snapshots', sa.Column('source_definition_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_source_snapshots_source_definition_id'), 'source_snapshots', ['source_definition_id'], unique=False)
    op.create_foreign_key('fk_source_snapshots_source_definition_id', 'source_snapshots', 'source_definitions', ['source_definition_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_source_snapshots_source_definition_id', 'source_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_source_snapshots_source_definition_id'), table_name='source_snapshots')
    op.drop_column('source_snapshots', 'source_definition_id')
    op.drop_index(op.f('ix_human_action_requests_state'), table_name='human_action_requests')
    op.drop_index(op.f('ix_human_action_requests_collection_job_id'), table_name='human_action_requests')
    op.drop_table('human_action_requests')
    op.drop_index(op.f('ix_collection_jobs_state'), table_name='collection_jobs')
    op.drop_index(op.f('ix_collection_jobs_source_definition_id'), table_name='collection_jobs')
    op.drop_index('idx_collection_job_state_requested', table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_source_definitions_pool_id'), table_name='source_definitions')
    op.drop_table('source_definitions')
    op.drop_index(op.f('ix_source_pools_dashboard_version_key'), table_name='source_pools')
    op.drop_table('source_pools')
    postgresql.ENUM(name='v2_human_action_state').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='v2_collection_job_state').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='v2_source_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
