"""add versioned dashboards and extraction runs

Revision ID: d59076df48fb
Revises: 1f4c9178d220
Create Date: 2026-07-24 17:38:52.518795
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd59076df48fb'
down_revision: Union[str, None] = '1f4c9178d220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('dashboard_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='v2_dashboard_version_state'), nullable=False),
    sa.Column('research_brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_model', sa.String(length=255), nullable=True),
    sa.Column('generation_prompt_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'version', name='uq_dashboard_version_number')
    )
    op.create_index(op.f('ix_dashboard_versions_dashboard_id'), 'dashboard_versions', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_versions_state'), 'dashboard_versions', ['state'], unique=False)
    op.create_table('panel_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'key', name='uq_panel_dashboard_key')
    )
    op.create_index(op.f('ix_panel_definitions_dashboard_id'), 'panel_definitions', ['dashboard_id'], unique=False)
    op.create_table('panel_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=False),
    sa.Column('dashboard_version_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_kind', sa.Enum('UI_DSL', 'CUSTOM_REACT', name='v2_panel_template_kind'), nullable=False),
    sa.Column('ui_dsl', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('component_code', sa.Text(), nullable=True),
    sa.Column('component_code_sha256', sa.String(length=64), nullable=True),
    sa.Column('visualization_contract', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_prompt', sa.Text(), nullable=False),
    sa.Column('extraction_prompt_version', sa.String(length=100), nullable=False),
    sa.Column('model_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_pool_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_version_id'], ['dashboard_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['panel_id'], ['panel_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_pool_id'], ['source_pools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'dashboard_version_id', name='uq_panel_dashboard_version'),
    sa.UniqueConstraint('panel_id', 'version', name='uq_panel_version_number')
    )
    op.create_index(op.f('ix_panel_versions_dashboard_version_id'), 'panel_versions', ['dashboard_version_id'], unique=False)
    op.create_index(op.f('ix_panel_versions_panel_id'), 'panel_versions', ['panel_id'], unique=False)
    op.create_index(op.f('ix_panel_versions_source_pool_id'), 'panel_versions', ['source_pool_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panel_version_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['panel_version_id'], ['panel_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_panel_version_id'), 'extraction_runs', ['panel_version_id'], unique=False)
    op.create_index(op.f('ix_extraction_runs_snapshot_id'), 'extraction_runs', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_runs_snapshot_id'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_panel_version_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_panel_versions_source_pool_id'), table_name='panel_versions')
    op.drop_index(op.f('ix_panel_versions_panel_id'), table_name='panel_versions')
    op.drop_index(op.f('ix_panel_versions_dashboard_version_id'), table_name='panel_versions')
    op.drop_table('panel_versions')
    op.drop_index(op.f('ix_panel_definitions_dashboard_id'), table_name='panel_definitions')
    op.drop_table('panel_definitions')
    op.drop_index(op.f('ix_dashboard_versions_state'), table_name='dashboard_versions')
    op.drop_index(op.f('ix_dashboard_versions_dashboard_id'), table_name='dashboard_versions')
    op.drop_table('dashboard_versions')
    op.drop_table('dashboards')
    postgresql.ENUM(name='v2_panel_template_kind').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='v2_dashboard_version_state').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
